defs["XLEN"] = {"value": "64"}

defs["PC_RESET_VALUE"] = {"value": "0x80000000", "prefix": "64"}


defs["ERRORCODE__ACCESS_FAULT"] = {"value": "0x0", "prefix": "64"}
defs["ERRORCODE__MISALIGNED_ADDRESS"] = {"value": "0x1", "prefix": "64"}

defs["SIZE__BYTE"] = {"value": "0x0", "prefix": "2"}
defs["SIZE__HALF_WORD"] = {"value": "0x1", "prefix": "2"}
defs["SIZE__WORD"] = {"value": "0x2", "prefix": "2"}
defs["SIZE__DOUBLE_WORD"] = {"value": "0x3", "prefix": "2"}

defs["FORMAT__R_TYPE"] = {"value": "0x0", "prefix": "3"}
defs["FORMAT__I_TYPE"] = {"value": "0x1", "prefix": "3"}
defs["FORMAT__S_TYPE"] = {"value": "0x2", "prefix": "3"}
defs["FORMAT__B_TYPE"] = {"value": "0x3", "prefix": "3"}
defs["FORMAT__U_TYPE"] = {"value": "0x4", "prefix": "3"}
defs["FORMAT__J_TYPE"] = {"value": "0x0", "prefix": "3"}

defs["OP__NOP"] = {"value": "0x0", "prefix": "6"}
defs["OP__LB"] = {"value": "0x1", "prefix": "6"}
defs["OP__LH"] = {"value": "0x2", "prefix": "6"}
defs["OP__LW"] = {"value": "0x3", "prefix": "6"}
defs["OP__LD"] = {"value": "0x4", "prefix": "6"}
defs["OP__LBU"] = {"value": "0x5", "prefix": "6"}
defs["OP__LHU"] = {"value": "0x6", "prefix": "6"}
defs["OP__LWU"] = {"value": "0x7", "prefix": "6"}
defs["OP__FENCE"] = {"value": "0x8", "prefix": "6"}
defs["OP__FENCE_I"] = {"value": "0x9", "prefix": "6"}
defs["OP__ADDI"] = {"value": "0xa", "prefix": "6"}
defs["OP__SLLI"] = {"value": "0xb", "prefix": "6"}
defs["OP__SLTI"] = {"value": "0xc", "prefix": "6"}
defs["OP__SLTIU"] = {"value": "0xd", "prefix": "6"}
defs["OP__XORI"] = {"value": "0xe", "prefix": "6"}
defs["OP__SRLI"] = {"value": "0xf", "prefix": "6"}
defs["OP__SRAI"] = {"value": "0x10", "prefix": "6"}
defs["OP__ORI"] = {"value": "0x11", "prefix": "6"}
defs["OP__ANDI"] = {"value": "0x12", "prefix": "6"}
defs["OP__AUIPC"] = {"value": "0x13", "prefix": "6"}
defs["OP__ADDIW"] = {"value": "0x14", "prefix": "6"}
defs["OP__SLLIW"] = {"value": "0x15", "prefix": "6"}
defs["OP__SRLIW"] = {"value": "0x16", "prefix": "6"}
defs["OP__SRAIW"] = {"value": "0x17", "prefix": "6"}
defs["OP__SB"] = {"value": "0x18", "prefix": "6"}
defs["OP__SH"] = {"value": "0x19", "prefix": "6"}
defs["OP__SW"] = {"value": "0x1a", "prefix": "6"}
defs["OP__SD"] = {"value": "0x1b", "prefix": "6"}
defs["OP__ADD"] = {"value": "0x1c", "prefix": "6"}
defs["OP__SUB"] = {"value": "0x1d", "prefix": "6"}
defs["OP__SLL"] = {"value": "0x1e", "prefix": "6"}
defs["OP__SLT"] = {"value": "0x1f", "prefix": "6"}
defs["OP__SLTU"] = {"value": "0x20", "prefix": "6"}
defs["OP__XOR"] = {"value": "0x21", "prefix": "6"}
defs["OP__SRL"] = {"value": "0x22", "prefix": "6"}
defs["OP__SRA"] = {"value": "0x23", "prefix": "6"}
defs["OP__OR"] = {"value": "0x24", "prefix": "6"}
defs["OP__AND"] = {"value": "0x25", "prefix": "6"}
defs["OP__LUI"] = {"value": "0x26", "prefix": "6"}
defs["OP__ADDW"] = {"value": "0x27", "prefix": "6"}
defs["OP__SUBW"] = {"value": "0x28", "prefix": "6"}
defs["OP__SLLW"] = {"value": "0x29", "prefix": "6"}
defs["OP__SRLW"] = {"value": "0x2a", "prefix": "6"}
defs["OP__SRAW"] = {"value": "0x2b", "prefix": "6"}
defs["OP__BEQ"] = {"value": "0x2c", "prefix": "6"}
defs["OP__BNE"] = {"value": "0x2d", "prefix": "6"}
defs["OP__BLT"] = {"value": "0x2e", "prefix": "6"}
defs["OP__BGE"] = {"value": "0x2f", "prefix": "6"}
defs["OP__BLTU"] = {"value": "0x30", "prefix": "6"}
defs["OP__BGEU"] = {"value": "0x31", "prefix": "6"}
defs["OP__JALR"] = {"value": "0x32", "prefix": "6"}
defs["OP__JAL"] = {"value": "0x33", "prefix": "6"}
defs["OP__ECALL"] = {"value": "0x34", "prefix": "6"}
defs["OP__EBREAK"] = {"value": "0x35", "prefix": "6"}
defs["OP__CSRRW"] = {"value": "0x36", "prefix": "6"}
defs["OP__CSRRS"] = {"value": "0x37", "prefix": "6"}
defs["OP__CSRRC"] = {"value": "0x38", "prefix": "6"}
defs["OP__CSRRWI"] = {"value": "0x39", "prefix": "6"}
defs["OP__CSRRSI"] = {"value": "0x3a", "prefix": "6"}
defs["OP__CSRRCI"] = {"value": "0x3b", "prefix": "6"}
defs["OP__MRET"] = {"value": "0x3c", "prefix": "6"}
defs["OP__WFI"] = {"value": "0x3d", "prefix": "6"}

defs["FUNC__ADD"] = {"value": "0x0", "prefix": "5"}
defs["FUNC__ADDW"] = {"value": "0x1", "prefix": "5"}
defs["FUNC__SUB"] = {"value": "0x2", "prefix": "5"}
defs["FUNC__SUBW"] = {"value": "0x3", "prefix": "5"}
defs["FUNC__SLL"] = {"value": "0x4", "prefix": "5"}
defs["FUNC__SLLW"] = {"value": "0x5", "prefix": "5"}
defs["FUNC__SLT"] = {"value": "0x6", "prefix": "5"}
defs["FUNC__SLTU"] = {"value": "0x7", "prefix": "5"}
defs["FUNC__XOR"] = {"value": "0x8", "prefix": "5"}
defs["FUNC__SRL"] = {"value": "0x9", "prefix": "5"}
defs["FUNC__SRLW"] = {"value": "0xa", "prefix": "5"}
defs["FUNC__SRA"] = {"value": "0xb", "prefix": "5"}
defs["FUNC__SRAW"] = {"value": "0xc", "prefix": "5"}
defs["FUNC__OR"] = {"value": "0xd", "prefix": "5"}
defs["FUNC__AND"] = {"value": "0xe", "prefix": "5"}
defs["FUNC__CLR"] = {"value": "0xf", "prefix": "5"}
defs["FUNC__NULL_A"] = {"value": "0x10", "prefix": "5"}
defs["FUNC__NULL_B"] = {"value": "0x11", "prefix": "5"}

defs["CSR__MISA"] = {"value": "0x301", "prefix": "12"}
defs["CSR__MISA__EXTENSIONS__FIELD"] = {"value": "25:0"}
defs["CSR__MISA__EXTENSIONS__WIDTH"] = {"value": "26"}
defs["CSR__MISA__EXTENSIONS__I"] = {"value": "0x100", "prefix": "26"}
defs["CSR__MISA__WIRI__0__FIELD"] = {"value": "61:26"}
defs["CSR__MISA__WIRI__0__WIDTH"] = {"value": "36"}
defs["CSR__MISA__WIRI__0__VALUE"] = {"value": "0x0", "prefix": "36"}
defs["CSR__MISA__BASE__FIELD"] = {"value": "63:62"}
defs["CSR__MISA__BASE__WIDTH"] = {"value": "2"}
defs["CSR__MISA__BASE__RV64"] = {"value": "0x2", "prefix": "2"}

#defs["CSR__MVENDORID"] = "12"hf11"
#defs["CSR__MVENDORID__VENDOR__FIELD"] = "63:0"
#defs["CSR__MVENDORID__VENDOR__WIDTH"] = "64"
#defs["CSR__MVENDORID__VENDOR__VALUE"] = "64"h0"
#
#defs["CSR__MARCHID"] = "12"hf12"
#defs["CSR__MARCHID__ARCHITECTURE_ID__FIELD"] = "63:0"
#defs["CSR__MARCHID__ARCHITECTURE_ID__WIDTH"] = "64"
#defs["CSR__MARCHID__ARCHITECTURE_ID__VALUE"] = "64"h0"
#
#defs["CSR__MIMPID"] = "12"hf13"
#defs["CSR__MIMPID__IMPLEMENTATION__FIELD"] = "63:0"
#defs["CSR__MIMPID__IMPLEMENTATION__WIDTH"] = "64"
#defs["CSR__MIMPID__IMPLEMENTATION__VALUE"] = "64"h0"
#
#defs["CSR__MHARTID"] = "12"hf14"
#defs["CSR__MHARTID__HART_ID__FIELD"] = "63:0"
#defs["CSR__MHARTID__HART_ID__WIDTH"] = "64"
#defs["CSR__MHARTID__HART_ID__VALUE"] = "64"h0"
#
#defs["CSR__MSTATUS"] = "12"h300"
#defs["CSR__MSTATUS__UIE__FIELD"] = "0"
#defs["CSR__MSTATUS__UIE__WIDTH"] = "1"
#defs["CSR__MSTATUS__UIE__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__UIE__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__SIE__FIELD"] = "1"
#defs["CSR__MSTATUS__SIE__WIDTH"] = "1"
#defs["CSR__MSTATUS__SIE__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__SIE__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__HIE__FIELD"] = "2"
#defs["CSR__MSTATUS__HIE__WIDTH"] = "1"
#defs["CSR__MSTATUS__HIE__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__HIE__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__MIE__FIELD"] = "3"
#defs["CSR__MSTATUS__MIE__WIDTH"] = "1"
#defs["CSR__MSTATUS__MIE__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__MIE__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__UPIE__FIELD"] = "4"
#defs["CSR__MSTATUS__UPIE__WIDTH"] = "1"
#defs["CSR__MSTATUS__UPIE__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__UPIE__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__SPIE__FIELD"] = "5"
#defs["CSR__MSTATUS__SPIE__WIDTH"] = "1"
#defs["CSR__MSTATUS__SPIE__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__SPIE__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__HPIE__FIELD"] = "6"
#defs["CSR__MSTATUS__HPIE__WIDTH"] = "1"
#defs["CSR__MSTATUS__HPIE__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__HPIE__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__MPIE__FIELD"] = "7"
#defs["CSR__MSTATUS__MPIE__WIDTH"] = "1"
#defs["CSR__MSTATUS__MPIE__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__MPIE__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__SPP__FIELD"] = "8"
#defs["CSR__MSTATUS__SPP__WIDTH"] = "1"
#defs["CSR__MSTATUS__SPP__USER"] = "1"b0"
#defs["CSR__MSTATUS__SPP__SUPERVISOR"] = "1"b1"
#defs["CSR__MSTATUS__HPP__FIELD"] = "10:9"
#defs["CSR__MSTATUS__HPP__WIDTH"] = "2"
#defs["CSR__MSTATUS__HPP__USER"] = "2"h0"
#defs["CSR__MSTATUS__HPP__SUPERVISOR"] = "2"h1"
#defs["CSR__MSTATUS__HPP__HYPERVISOR"] = "2"h2"
#defs["CSR__MSTATUS__MPP__FIELD"] = "12:11"
#defs["CSR__MSTATUS__MPP__WIDTH"] = "2"
#defs["CSR__MSTATUS__MPP__USER"] = "2"h0"
#defs["CSR__MSTATUS__MPP__SUPERVISOR"] = "2"h1"
#defs["CSR__MSTATUS__MPP__HYPERVISOR"] = "2"h2"
#defs["CSR__MSTATUS__MPP__MACHINE"] = "2"h3"
#defs["CSR__MSTATUS__FS__FIELD"] = "14:13"
#defs["CSR__MSTATUS__FS__WIDTH"] = "2"
#defs["CSR__MSTATUS__FS__OFF"] = "2"h0"
#defs["CSR__MSTATUS__FS__INITIAL"] = "2"h1"
#defs["CSR__MSTATUS__FS__CLEAN"] = "2"h2"
#defs["CSR__MSTATUS__FS__DIRTY"] = "2"h3"
#defs["CSR__MSTATUS__XS__FIELD"] = "16:15"
#defs["CSR__MSTATUS__XS__WIDTH"] = "2"
#defs["CSR__MSTATUS__XS__OFF"] = "2"h0"
#defs["CSR__MSTATUS__XS__INITIAL"] = "2"h1"
#defs["CSR__MSTATUS__XS__CLEAN"] = "2"h2"
#defs["CSR__MSTATUS__XS__DIRTY"] = "2"h3"
#defs["CSR__MSTATUS__MPRV__FIELD"] = "17"
#defs["CSR__MSTATUS__MPRV__WIDTH"] = "1"
#defs["CSR__MSTATUS__MPRV__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__MPRV__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__PUM__FIELD"] = "18"
#defs["CSR__MSTATUS__PUM__WIDTH"] = "1"
#defs["CSR__MSTATUS__PUM__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__PUM__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__MXR__FIELD"] = "19"
#defs["CSR__MSTATUS__MXR__WIDTH"] = "1"
#defs["CSR__MSTATUS__MXR__DISABLED"] = "1"b0"
#defs["CSR__MSTATUS__MXR__ENABLED"] = "1"b1"
#defs["CSR__MSTATUS__WPRI__0__FIELD"] = "23:20"
#defs["CSR__MSTATUS__WPRI__0__WIDTH"] = "4"
#defs["CSR__MSTATUS__WPRI__0__RESET_VALUE"] = "4"h0"
#defs["CSR__MSTATUS__VM__FIELD"] = "28:24"
#defs["CSR__MSTATUS__VM__WIDTH"] = "5"
#defs["CSR__MSTATUS__VM__MBARE"] = "5"h0"
#defs["CSR__MSTATUS__VM__MBB"] = "5"h1"
#defs["CSR__MSTATUS__VM__MBBID"] = "5"h2"
#defs["CSR__MSTATUS__VM__SV32"] = "5"h8"
#defs["CSR__MSTATUS__VM__SV39"] = "5"h9"
#defs["CSR__MSTATUS__VM__SV48"] = "5"ha"
#defs["CSR__MSTATUS__VM__SV57"] = "5"hb"
#defs["CSR__MSTATUS__VM__SV64"] = "5"hc"
#defs["CSR__MSTATUS__WPRI__1__FIELD"] = "62:29"
#defs["CSR__MSTATUS__WPRI__1__WIDTH"] = "33"
#defs["CSR__MSTATUS__WPRI__1__RESET_VALUE"] = "33"h0"
#defs["CSR__MSTATUS__SD__FIELD"] = "63"
#defs["CSR__MSTATUS__SD__WIDTH"] = "1"
#defs["CSR__MSTATUS__SD__NOT_DIRTY"] = "1"b0"
#defs["CSR__MSTATUS__SD__DIRTY"] = "1"b1"
#
#defs["CSR__MTVEC"] = "12"h305"
#defs["CSR__MTVEC__OFFSET__FIELD"] = "1:0"
#defs["CSR__MTVEC__OFFSET__WIDTH"] = "2"
#defs["CSR__MTVEC__OFFSET__VALUE"] = "2"h0"
#defs["CSR__MTVEC__TRAP_VECTOR_BASE_ADDRESS__FIELD"] = "63:2"
#defs["CSR__MTVEC__TRAP_VECTOR_BASE_ADDRESS__WIDTH"] = "62"
#defs["CSR__MTVEC__TRAP_VECTOR_BASE_ADDRESS__VALUE"] = "62"h0"
#
#defs["CSR__MEDELEG"] = "12"h302"
#defs["CSR__MEDELEG__SYNCHRONOUS_EXCEPTIONS__FIELD"] = "63:0"
#defs["CSR__MEDELEG__SYNCHRONOUS_EXCEPTIONS__WIDTH"] = "64"
#defs["CSR__MEDELEG__SYNCHRONOUS_EXCEPTIONS__VALUE"] = "64"h0"
#
#defs["CSR__MIDELEG"] = "12"h303"
#defs["CSR__MIDELEG__INTERRUPTS__FIELD"] = "63:0"
#defs["CSR__MIDELEG__INTERRUPTS__WIDTH"] = "64"
#defs["CSR__MIDELEG__INTERRUPTS__VALUE"] = "64"h0"
#
#defs["CSR__MIP"] = "12"h344"
#defs["CSR__MIP__USIP__FIELD"] = "0"
#defs["CSR__MIP__USIP__WIDTH"] = "1"
#defs["CSR__MIP__USIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__USIP__PENDING"] = "1"b1"
#defs["CSR__MIP__SSIP__FIELD"] = "1"
#defs["CSR__MIP__SSIP__WIDTH"] = "1"
#defs["CSR__MIP__SSIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__SSIP__PENDING"] = "1"b1"
#defs["CSR__MIP__HSIP__FIELD"] = "2"
#defs["CSR__MIP__HSIP__WIDTH"] = "1"
#defs["CSR__MIP__HSIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__HSIP__PENDING"] = "1"b1"
#defs["CSR__MIP__MSIP__FIELD"] = "3"
#defs["CSR__MIP__MSIP__WIDTH"] = "1"
#defs["CSR__MIP__MSIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__MSIP__PENDING"] = "1"b1"
#defs["CSR__MIP__UTIP__FIELD"] = "4"
#defs["CSR__MIP__UTIP__WIDTH"] = "1"
#defs["CSR__MIP__UTIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__UTIP__PENDING"] = "1"b1"
#defs["CSR__MIP__STIP__FIELD"] = "5"
#defs["CSR__MIP__STIP__WIDTH"] = "1"
#defs["CSR__MIP__STIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__STIP__PENDING"] = "1"b1"
#defs["CSR__MIP__HTIP__FIELD"] = "6"
#defs["CSR__MIP__HTIP__WIDTH"] = "1"
#defs["CSR__MIP__HTIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__HTIP__PENDING"] = "1"b1"
#defs["CSR__MIP__MTIP__FIELD"] = "7"
#defs["CSR__MIP__MTIP__WIDTH"] = "1"
#defs["CSR__MIP__MTIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__MTIP__PENDING"] = "1"b1"
#defs["CSR__MIP__UEIP__FIELD"] = "8"
#defs["CSR__MIP__UEIP__WIDTH"] = "1"
#defs["CSR__MIP__UEIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__UEIP__PENDING"] = "1"b1"
#defs["CSR__MIP__SEIP__FIELD"] = "9"
#defs["CSR__MIP__SEIP__WIDTH"] = "1"
#defs["CSR__MIP__SEIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__SEIP__PENDING"] = "1"b1"
#defs["CSR__MIP__HEIP__FIELD"] = "10"
#defs["CSR__MIP__HEIP__WIDTH"] = "1"
#defs["CSR__MIP__HEIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__HEIP__PENDING"] = "1"b1"
#defs["CSR__MIP__MEIP__FIELD"] = "11"
#defs["CSR__MIP__MEIP__WIDTH"] = "1"
#defs["CSR__MIP__MEIP__NOT_PENDING"] = "1"b0"
#defs["CSR__MIP__MEIP__PENDING"] = "1"b1"
#defs["CSR__MIP__WIRI__0__FIELD"] = "63:12"
#defs["CSR__MIP__WIRI__0__WIDTH"] = "52"
#defs["CSR__MIP__WIRI__0__VALUE"] = "52"h0"
#
#defs["CSR__MIE"] = "12"h304"
#defs["CSR__MIE__USIE__FIELD"] = "0"
#defs["CSR__MIE__USIE__WIDTH"] = "1"
#defs["CSR__MIE__USIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__USIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__SSIE__FIELD"] = "1"
#defs["CSR__MIE__SSIE__WIDTH"] = "1"
#defs["CSR__MIE__SSIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__SSIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__HSIE__FIELD"] = "2"
#defs["CSR__MIE__HSIE__WIDTH"] = "1"
#defs["CSR__MIE__HSIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__HSIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__MSIE__FIELD"] = "3"
#defs["CSR__MIE__MSIE__WIDTH"] = "1"
#defs["CSR__MIE__MSIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__MSIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__UTIE__FIELD"] = "4"
#defs["CSR__MIE__UTIE__WIDTH"] = "1"
#defs["CSR__MIE__UTIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__UTIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__STIE__FIELD"] = "5"
#defs["CSR__MIE__STIE__WIDTH"] = "1"
#defs["CSR__MIE__STIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__STIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__HTIE__FIELD"] = "6"
#defs["CSR__MIE__HTIE__WIDTH"] = "1"
#defs["CSR__MIE__HTIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__HTIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__MTIE__FIELD"] = "7"
#defs["CSR__MIE__MTIE__WIDTH"] = "1"
#defs["CSR__MIE__MTIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__MTIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__UEIE__FIELD"] = "8"
#defs["CSR__MIE__UEIE__WIDTH"] = "1"
#defs["CSR__MIE__UEIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__UEIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__SEIE__FIELD"] = "9"
#defs["CSR__MIE__SEIE__WIDTH"] = "1"
#defs["CSR__MIE__SEIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__SEIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__HEIE__FIELD"] = "10"
#defs["CSR__MIE__HEIE__WIDTH"] = "1"
#defs["CSR__MIE__HEIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__HEIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__MEIE__FIELD"] = "11"
#defs["CSR__MIE__MEIE__WIDTH"] = "1"
#defs["CSR__MIE__MEIE__DISABLED"] = "1"b0"
#defs["CSR__MIE__MEIE__ENABLED"] = "1"b1"
#defs["CSR__MIE__WPRI__0__FIELD"] = "63:12"
#defs["CSR__MIE__WPRI__0__WIDTH"] = "52"
#defs["CSR__MIE__WPRI__0__VALUE"] = "52"h0"
#
#defs["CSR__MTIME"] = "12"h0"
#defs["CSR__MTIME__MTIME__FIELD"] = "63:0"
#defs["CSR__MTIME__MTIME__WIDTH"] = "64"
#defs["CSR__MTIME__MTIME__RESET_VALUE"] = "64"h0"
#
#defs["CSR__MTIMECMP"] = "12"h0"
#defs["CSR__MTIMECMP__MTIMECMP__FIELD"] = "63:0"
#defs["CSR__MTIMECMP__MTIMECMP__WIDTH"] = "64"
#defs["CSR__MTIMECMP__MTIMECMP__RESET_VALUE"] = "64"h0"
#
#defs["CSR__MCYCLE"] = "12"hb00"
#defs["CSR__MCYCLE__MCYCLE__FIELD"] = "63:0"
#defs["CSR__MCYCLE__MCYCLE__WIDTH"] = "64"
#defs["CSR__MCYCLE__MCYCLE__RESET_VALUE"] = "64"h0"
#
#defs["CSR__MINSTRET"] = "12"hb02"
#defs["CSR__MINSTRET__MINSTRET__FIELD"] = "63:0"
#defs["CSR__MINSTRET__MINSTRET__WIDTH"] = "64"
#defs["CSR__MINSTRET__MINSTRET__RESET_VALUE"] = "64"h0"
#
#defs["CSR__MHPMCOUNTER3"] = "12"hb03"
#defs["CSR__MHPMCOUNTER3__MHPMCOUNTER3__FIELD"] = "63:0"
#defs["CSR__MHPMCOUNTER3__MHPMCOUNTER3__WIDTH"] = "64"
#defs["CSR__MHPMCOUNTER3__MHPMCOUNTER3__VALUE"] = "64"h0"
#
#defs["CSR__MHPMEVENT3"] = "12"h323"
#defs["CSR__MHPMEVENT3__MHPMEVENT3__FIELD"] = "63:0"
#defs["CSR__MHPMEVENT3__MHPMEVENT3__WIDTH"] = "64"
#defs["CSR__MHPMEVENT3__MHPMEVENT3__VALUE"] = "64"h0"
#
#defs["CSR__MSCRATCH"] = "12"h340"
#defs["CSR__MSCRATCH__MSCRATCH__FIELD"] = "63:0"
#defs["CSR__MSCRATCH__MSCRATCH__WIDTH"] = "64" 
#defs["CSR__MSCRATCH__MSCRATCH__RESET_VALUE"] = "64"h0"
#
#defs["CSR__MEPC"] = "12"h341"
#defs["CSR__MEPC__MEPC__FIELD"] = "63:0"
#defs["CSR__MEPC__MEPC__WIDTH"] = "64"
#defs["CSR__MEPC__MEPC__RESET_VALUE"] = "64"h0"
#
#defs["CSR__MCAUSE"] = "12"h342"
#defs["CSR__MCAUSE__EXCEPTION_CODE__FIELD"] = "62:0"
#defs["CSR__MCAUSE__EXCEPTION_CODE__WIDTH"] = "63"
#defs["CSR__MCAUSE__EXCEPTION_CODE__HARD_RESET"] = "63"h0"
#defs["CSR__MCAUSE__EXCEPTION_CODE__INSTRUCTION_ADDRESS_MISALIGNED"] = "63"h0"
#defs["CSR__MCAUSE__EXCEPTION_CODE__INSTRUCTION_ACCESS_FAULT"] = "63"h1"
#defs["CSR__MCAUSE__EXCEPTION_CODE__ILLEGAL_INSTRUCTION"] = "63"h2"
#defs["CSR__MCAUSE__EXCEPTION_CODE__BREAKPOINT"] = "63"h3"
#defs["CSR__MCAUSE__EXCEPTION_CODE__LOAD_ADDRESS_MISALIGNED"] = "63"h4"
#defs["CSR__MCAUSE__EXCEPTION_CODE__LOAD_ACCESS_FAULT"] = "63"h5"
#defs["CSR__MCAUSE__EXCEPTION_CODE__STORE_ADDRESS_MISALIGNED"] = "63"h6"
#defs["CSR__MCAUSE__EXCEPTION_CODE__STORE_ACCESS_FAULT"] = "63"h7"
#defs["CSR__MCAUSE__EXCEPTION_CODE__ENVIRONMENT_CALL_FROM_U_MODE"] = "63"h8"
#defs["CSR__MCAUSE__EXCEPTION_CODE__ENVIRONMENT_CALL_FROM_S_MODE"] = "63"h9"
#defs["CSR__MCAUSE__EXCEPTION_CODE__ENVIRONMENT_CALL_FROM_H_MODE"] = "63"ha"
#defs["CSR__MCAUSE__EXCEPTION_CODE__ENVIRONMENT_CALL_FROM_M_MODE"] = "63"hb"
#defs["CSR__MCAUSE__EXCEPTION_CODE__MACHINE_SOFTWARE_INTERRUPT"] = "63"h3"
#defs["CSR__MCAUSE__EXCEPTION_CODE__MACHINE_TIMER_INTERRUPT"] = "63"h7"
#defs["CSR__MCAUSE__EXCEPTION_CODE__MACHINE_EXTERNAL_INTERRUPT"] = "63"hb"
#defs["CSR__MCAUSE__INTERRUPT__FIELD"] = "63"
#defs["CSR__MCAUSE__INTERRUPT__WIDTH"] = "1"
#defs["CSR__MCAUSE__INTERRUPT__NOT_INTERRUPT"] = "1"b0"
#defs["CSR__MCAUSE__INTERRUPT__INTERRUPT"] = "1"b1"
#
#defs["CSR__MTVAL"] = "12"h343"
#defs["CSR__MTVAL__MTVAL__FIELD"] = "63:0"
#defs["CSR__MTVAL__MTVAL__WIDTH"] = "64"
#defs["CSR__MTVAL__MTVAL__RESET_VALUE"] = "64"h0"
#
#
#
#defs["MEMORY_MAPPED_REGION__0"] = "64"b0000_0000__0000_0000__0000_0000__0000_0000__1000_????__????_????__????_????__????_????"
#defs["MEMORY_MAPPED_REGION__1"] = "64"b0000_0000__0000_0000__0000_0000__0000_0000__1001_????__????_????__????_????__????_????"
#defs["MEMORY_MAPPED_REGION__2"] = "64"b0000_0000__0000_0000__0000_0000__0000_0000__1010_????__????_????__????_????__????_????"
#defs["MEMORY_MAPPED_REGION__3"] = "64"b0000_0000__0000_0000__0000_0000__0000_0000__1011_????__????_????__????_????__????_????"
#defs["MEMORY_MAPPED_REGION__4"] = "64"b0000_0000__0000_0000__0000_0000__0000_0000__1100_????__????_????__????_????__????_????"
#defs["MEMORY_MAPPED_REGION__5"] = "64"b0000_0000__0000_0000__0000_0000__0000_0000__1101_????__????_????__????_????__????_????"
#defs["MEMORY_MAPPED_REGION__6"] = "64"b0000_0000__0000_0000__0000_0000__0000_0000__1110_????__????_????__????_????__????_????"
#defs["MEMORY_MAPPED_REGION__7"] = "64"b0000_0000__0000_0000__0000_0000__0000_0000__1111_????__????_????__????_????__????_????"
#
#defs["PLATFORM_LEVEL_INTERRUPT_CONTROLLER__BASE_ADDR"] = "40"b0000_0000_1001__0000_0000_0000_0000_0000_0000_0000"
#defs["PLATFORM_LEVEL_INTERRUPT_CONTROLLER__INTERRUPT_SOURCE_PRIORITY__0"] = "26"h0_00_00_00"
#defs["PLATFORM_LEVEL_INTERRUPT_CONTROLLER__INTERRUPT_SOURCE_PRIORITY__1"] = "26"h0_00_00_04"
#defs["PLATFORM_LEVEL_INTERRUPT_CONTROLLER__INTERRUPT_PENDING_BITS__0_TO_31"] = "26"h0_00_10_00"
#defs["PLATFORM_LEVEL_INTERRUPT_CONTROLLER__INTERRUPT_ENABLE_BITS__0_TO_31__CONTEXT__0"] = "26"h0_00_20_00"
#defs["PLATFORM_LEVEL_INTERRUPT_CONTROLLER__PRIORITY_THRESHOLD__CONTEXT__0"] = "26"h20_00_00"
#defs["PLATFORM_LEVEL_INTERRUPT_CONTROLLER__INTERRUPT_CLAIM_COMPLETE__CONTEXT__0"] = "26"h20_00_04"
#
#
#defs["MACHINE_TIMER_REGISTERS__BASE_ADDR"] = "40"b0000_0000_1010__0000_0000_0000_0000_0000_0000_0000"
#defs["MACHINE_TIMER_REGISTERS__MTIME"] = "1"b0"
#defs["MACHINE_TIMER_REGISTERS__MTIMECMP"] = "1"b1"
#
#
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__BASE_ADDR"] = "40"b0000_0000_1011__0000_0000_0000_0000_0000_0000_0000"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__0"] = "3"h0"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__1"] = "3"h1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__2"] = "3"h2"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__3"] = "3"h3"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__4"] = "3"h0"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__5"] = "3"h1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__6"] = "3"h2"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__7"] = "3"h3"
#
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__MEMORY_TYPE__FIELD"] = "0:0"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__MEMORY_TYPE__WIDTH"] = "1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__MEMORY_TYPE__IO"] = "0"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__MEMORY_TYPE__MAIN_MEMORY"] = "1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__BYTE_ACCESS_SUPPORTED__FIELD"] = "1:1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__BYTE_ACCESS_SUPPORTED__WIDTH"] = "1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__HALF_WORD_ACCESS_SUPPORTED__FIELD"] = "2:2"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__HALF_WORD_ACCESS_SUPPORTED__WIDTH"] = "1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__WORD_ACCESS_SUPPORTED__FIELD"] = "3:3"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__WORD_ACCESS_SUPPORTED__WIDTH"] = "1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__DOUBLE_WORD_ACCESS_SUPPORTED__FIELD"] = "4:4"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__DOUBLE_WORD_ACCESS_SUPPORTED__WIDTH"] = "1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__MISALIGNED_ACCESS_SUPPORTED__FIELD"] = "5:5"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_REGISTER__MISALIGNED_ACCESS_SUPPORTED__WIDTH"] = "1"
#
#defs["PHYSICAL_MEMORY_ATTRIBUTE_CHECKER__STATUS__OK"] = "2"h0"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_CHECKER__STATUS__ACCESS_FAULT"] = "2"h1"
#defs["PHYSICAL_MEMORY_ATTRIBUTE_CHECKER__STATUS__MISALIGNED_ADDRESS"] = "2"h2"
#
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__BASE_ADDR"] = "40"b0000_0000_1100__0000_0000_0000_0000_0000_0000_0000"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__PORT__0"] = "4"h0"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__DATA__0"] = "4"h1"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__OE__0"] = "4"h2"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__PORT__1"] = "4"h3"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__DATA__1"] = "4"h4"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__OE__1"] = "4"h5"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__PORT__2"] = "4"h6"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__DATA__2"] = "4"h7"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__OE__2"] = "4"h8"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__PORT__3"] = "4"h9"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__DATA__3"] = "4"ha"
#defs["GENERAL_PURPOSE_INPUT_OUTPUT__OE__3"] = "4"hb"

