#===============================================
# Project Directories 
#===============================================
BLUEJAY := /home/seankent/bluejay
TOOLS := $(BLUEJAY)/tools

all:
	echo TEST 1, 2, 3

