bluejay = /mnt/c/Users/seanj/Documents/bluejay/
tools = tools/

run:
	python3 $(bluejay)$(tools)build.py register_file.b

#python3 bluejay/tools/build.by $@

# %.b:
# 	python3 $(bluejay)$(tools)build.py $@ ./ ./