# directory variables
bluejay = /mnt/c/Users/seanj/Documents/bluejay/
src = src/
tb = tb/
tools = tools/

build:
	python3 $(bluejay)$(tools)build.py register_file.b

#python3 bluejay/tools/build.by $@

# %.b:
# 	python3 $(bluejay)$(tools)build.py $@ ./ ./