webtalk_init -webtalk_dir /home/seankent/bluejay/ip/central_processing_unit/sim/xsim.dir/central_processing_unit__tb__snapshot/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan 21 18:46:39 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e3168381-eee8-4956-8b80-0d204ac8deb7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c595cc0d-1140-4706-a83b-e88fae104bf2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "66" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "113310 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.15_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "128168_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2337405159 -regid "" -xml /home/seankent/bluejay/ip/central_processing_unit/sim/xsim.dir/central_processing_unit__tb__snapshot/webtalk/usage_statistics_ext_xsim.xml -html /home/seankent/bluejay/ip/central_processing_unit/sim/xsim.dir/central_processing_unit__tb__snapshot/webtalk/usage_statistics_ext_xsim.html -wdm /home/seankent/bluejay/ip/central_processing_unit/sim/xsim.dir/central_processing_unit__tb__snapshot/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
