#define XLEN 64
#define PC_RESET_VALUE 0x80000000
#define ERRORCODE__ACCESS_FAULT 0x0
#define ERRORCODE__MISALIGNED_ADDRESS 0x1
#define SIZE__BYTE 0x0
#define SIZE__HALF_WORD 0x1
#define SIZE__WORD 0x2
#define SIZE__DOUBLE_WORD 0x3
#define FORMAT__R_TYPE 0x0
#define FORMAT__I_TYPE 0x1
#define FORMAT__S_TYPE 0x2
#define FORMAT__B_TYPE 0x3
#define FORMAT__U_TYPE 0x4
#define FORMAT__J_TYPE 0x0
#define OP__NOP 0x0
#define OP__LB 0x1
#define OP__LH 0x2
#define OP__LW 0x3
#define OP__LD 0x4
#define OP__LBU 0x5
#define OP__LHU 0x6
#define OP__LWU 0x7
#define OP__FENCE 0x8
#define OP__FENCE_I 0x9
#define OP__ADDI 0xa
#define OP__SLLI 0xb
#define OP__SLTI 0xc
#define OP__SLTIU 0xd
#define OP__XORI 0xe
#define OP__SRLI 0xf
#define OP__SRAI 0x10
#define OP__ORI 0x11
#define OP__ANDI 0x12
#define OP__AUIPC 0x13
#define OP__ADDIW 0x14
#define OP__SLLIW 0x15
#define OP__SRLIW 0x16
#define OP__SRAIW 0x17
#define OP__SB 0x18
#define OP__SH 0x19
#define OP__SW 0x1a
#define OP__SD 0x1b
#define OP__ADD 0x1c
#define OP__SUB 0x1d
#define OP__SLL 0x1e
#define OP__SLT 0x1f
#define OP__SLTU 0x20
#define OP__XOR 0x21
#define OP__SRL 0x22
#define OP__SRA 0x23
#define OP__OR 0x24
#define OP__AND 0x25
#define OP__LUI 0x26
#define OP__ADDW 0x27
#define OP__SUBW 0x28
#define OP__SLLW 0x29
#define OP__SRLW 0x2a
#define OP__SRAW 0x2b
#define OP__BEQ 0x2c
#define OP__BNE 0x2d
#define OP__BLT 0x2e
#define OP__BGE 0x2f
#define OP__BLTU 0x30
#define OP__BGEU 0x31
#define OP__JALR 0x32
#define OP__JAL 0x33
#define OP__ECALL 0x34
#define OP__EBREAK 0x35
#define OP__CSRRW 0x36
#define OP__CSRRS 0x37
#define OP__CSRRC 0x38
#define OP__CSRRWI 0x39
#define OP__CSRRSI 0x3a
#define OP__CSRRCI 0x3b
#define OP__MRET 0x3c
#define OP__WFI 0x3d
#define FUNC__ADD 0x0
#define FUNC__ADDW 0x1
#define FUNC__SUB 0x2
#define FUNC__SUBW 0x3
#define FUNC__SLL 0x4
#define FUNC__SLLW 0x5
#define FUNC__SLT 0x6
#define FUNC__SLTU 0x7
#define FUNC__XOR 0x8
#define FUNC__SRL 0x9
#define FUNC__SRLW 0xa
#define FUNC__SRA 0xb
#define FUNC__SRAW 0xc
#define FUNC__OR 0xd
#define FUNC__AND 0xe
#define FUNC__CLR 0xf
#define FUNC__NULL_A 0x10
#define FUNC__NULL_B 0x11
#define CSR__MISA 0x301
#define CSR__MISA__EXTENSIONS__FIELD 25:0
#define CSR__MISA__EXTENSIONS__WIDTH 26
#define CSR__MISA__EXTENSIONS__I 0x100
#define CSR__MISA__WIRI__0__FIELD 61:26
#define CSR__MISA__WIRI__0__WIDTH 36
#define CSR__MISA__WIRI__0__VALUE 0x0
#define CSR__MISA__BASE__FIELD 63:62
#define CSR__MISA__BASE__WIDTH 2
#define CSR__MISA__BASE__RV64 0x2
